name: CD

on:
  - push

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          workload_identity_provider: projects/685817651360/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-action-runner@tosuke-apps.iam.gserviceaccount.com 
      - name: gcloud
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"